export const NameScreen = {
    Login:'Login',
    Regist:'DangKyTaiKhoan',
    ThongTinTaiKhoan:'ThongTinTaiKhoan',
    DanhSachDonVi: 'DanhSachDonVi',
    TongCongTy: 'TongCongTy',
    TaoDuAn:'TaoDuAn',
    BaoCaoDuAn:'BaoCaoDuAn',
    CongViec:'CongViec',
    BaoCaoVanBan:'BaoCaoVanBan',
    MainPage:'MainPage',
    TrangChu:'TrangChu',
    Baotri: 'Baotri',
    GiaoViec: 'GiaoViec',
    ChamCong: 'ChamCong',
    ChamCongGPS:'ChamCongGPS',
    NghiPhep:'NghiPhep',
    BangCong:'BangCong',
    
    DuyetDeXuat:'DuyetDeXuat',
    TaiLieu:'TaiLieu',
    PhieuLuong:'PhieuLuong',
    TaiSan:'TaiSan',
    DanhSachDuAn:'DanhSachDuAn',
    CongViecDuAn:'CongViecDuAn',
    DuyetHoSo:'DuyetHoSo',
   
    DuanDrive:'DuanDrive',
    CongViecDrive:'CongViecDrive',
    HopDongDrive:'HopDongDrive',

    //DaMi
    Tonghophanghoa:'Report',
    Phieubanhang:'Invoice',
    Dangkyurl:'Setupurl',
    Thongbao:'Thongbao',
}