require Pod::Executable.execute_command('node', ['-p',
  "require.resolve('react-native/scripts/react_native_pods.rb', {paths: [process.argv[1]]})", __dir__]).strip

def node_require(script)
  require Pod::Executable.execute_command('node', ['-p',
    "require.resolve('#{script}', {paths: [process.argv[1]]})", __dir__]).strip
end

node_require('react-native/scripts/react_native_pods.rb')
node_require('react-native-permissions/scripts/setup.rb')

$RNFirebaseAsStaticFramework = true

platform :ios, min_ios_version_supported
use_frameworks!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

prepare_react_native_project!

target 'DaMiSaleReport' do
  ENV['NODE_BINARY'] = '/opt/homebrew/bin/node' # thêm dòng này
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :hermes_enabled => true
  )

  setup_permissions([
    'Camera',
    'PhotoLibrary',
    'Microphone',
    'LocationWhenInUse',
    'Bluetooth',
    'SpeechRecognition',
    'AppTrackingTransparency',
    'Contacts'
  ])

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    # ✅ Fix thiếu dSYM cho Hermes khi Archive
        installer.pods_project.targets.each do |target|
          if target.name == 'hermes-engine'
            target.build_configurations.each do |config|
              config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf-with-dsym'
          end
        end
      end
    end
end
